services:
  # Backend API Service
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://ecommerce-frontend.onrender.com

  # Frontend React App
  - type: web
    name: ecommerce-frontend
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ecommerce-backend.onrender.com
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 